# almasena-dev/ship_system/config/low_level_config.yaml

network:
  gcs_ip: "100.81.234.32"          # Diarahkan ke IP Ubuntu VirtualBox lu
  ship_ip: "100.64.105.25"         # IP Raspberry Pi 4 Kapal
  telemetry_port: 5006            # Disamakan dengan recv_port di main_gcs.py
  video_port_front: 5000
  video_port_bottom: 5001

hardware:
  stm32_port: "/dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_066EFF383430484257144950-if02"      # Sementara biarkan sama, toh nanti muncul baris WARN saja
  pixhawk_port: "/dev/serial/by-id/usb-ArduPilot_Pixhawk1_2F0039000D51373336363539-if00"    # Dibedakan agar tidak bentrok port serial virtualnya
  serial_baudrate: 115200

vision:
  model_path: "/home/almasena/almasena-dev/ship_system/src/models/yolov8n.pt" # Jalur absolut tanpa tilde
  cam_front: "/dev/cam_front"
  cam_bottom: "/dev/cam_bottom"
